# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.7

CABAL_FEATURES=""
inherit haskell-cabal

DESCRIPTION="Example programs for Qtah Qt bindings"
HOMEPAGE="http://khumba.net/projects/qtah"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="LGPL-3+"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/hoppy-runtime-0.8:= <dev-haskell/hoppy-runtime-0.9:=
	>=dev-haskell/qtah-qt5-0.8:= <dev-haskell/qtah-qt5-0.9:=
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.0
"
