# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.4

CABAL_FEATURES=""
inherit haskell-cabal

DESCRIPTION="Example programs for Qtah Qt bindings"
HOMEPAGE="http://khumba.net/projects/qtah"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="LGPL-3+"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/hoppy-runtime-0.4:= <dev-haskell/hoppy-runtime-0.5:=
	>=dev-haskell/qtah-qt5-0.4:= <dev-haskell/qtah-qt5-0.5:=
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"
