EAPI=6

# ebuild generated by hackport 0.5

CABAL_FEATURES="bin"
inherit git-r3 haskell-cabal

DESCRIPTION="Example programs for Qtah Qt bindings"
HOMEPAGE="http://khumba.net/projects/qtah"
EGIT_REPO_URI="https://gitlab.com/khumba/qtah.git"
S="${WORKDIR}/${P}/${PN}"

LICENSE="LGPL-3+"
SLOT="0"
KEYWORDS=""
IUSE="qt4 qt5"
REQUIRED_USE="^^ ( qt4 qt5 )"

RDEPEND=">=dev-haskell/binary-0.7:= <dev-haskell/binary-0.8:=
	>=dev-haskell/hoppy-runtime-0.2:=
	>=dev-haskell/qtah-9999:=[qt4=,qt5=]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"
