# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Example programs for Qtah Qt bindings"
HOMEPAGE="http://khumba.net/projects/qtah"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="LGPL-3+"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/binary-0.7:= <dev-haskell/binary-0.8:=
	>=dev-haskell/hoppy-runtime-0.2:= <dev-haskell/hoppy-runtime-0.3:=
	>=dev-haskell/qtah-qt5-0.1:= <dev-haskell/qtah-qt5-0.2:=
	>=dev-lang/ghc-7.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.16.0
"
