# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.5

CABAL_FEATURES=""
inherit git-r3 haskell-cabal

DESCRIPTION="Example programs for Qtah Qt bindings"
HOMEPAGE="http://khumba.net/projects/qtah"
EGIT_REPO_URI="https://gitlab.com/khumba/qtah.git"
S="${WORKDIR}/${P}/${PN}"

LICENSE="LGPL-3+"
SLOT="0"
KEYWORDS=""
IUSE="qt4 qt5"
REQUIRED_USE="^^ ( qt4 qt5 )"

RDEPEND=">=dev-haskell/hoppy-runtime-0.8:=
	>=dev-haskell/qtah-9999:=[qt4=,qt5=]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.0
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag qt4) \
		$(cabal_flag qt5)
}
