EAPI=6

# ebuild generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit git-r3 haskell-cabal

DESCRIPTION="Qt bindings for Haskell"
HOMEPAGE="http://khumba.net/projects/qtah"
EGIT_REPO_URI="https://gitlab.com/khumba/qtah.git"
S="${WORKDIR}/${P}/${PN}/hs"

LICENSE="LGPL-3+"
SLOT="0/${PV}"
KEYWORDS=""
IUSE="qt4 qt5"
REQUIRED_USE="^^ ( qt4 qt5 )"

RDEPEND=">=dev-haskell/binary-0.7:=[profile?] <dev-haskell/binary-0.8:=[profile?]
	>=dev-haskell/hoppy-runtime-0.2:=[profile?]
	>=dev-haskell/qtah-cpp-9999:=[qt4=,qt5=]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
	>=dev-haskell/qtah-generator-9999:=[qt4=,qt5=]
	test? ( >=dev-haskell/hunit-1.2 <dev-haskell/hunit-1.4 )
"

src_prepare() {
	qtah-generator --gen-hs "${S}/src" || die
	eapply_user
}
