# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

# ebuild generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit git-r3 haskell-cabal

DESCRIPTION="Qt bindings for Haskell"
HOMEPAGE="http://khumba.net/projects/qtah"
EGIT_REPO_URI="https://gitlab.com/khumba/qtah.git"
S="${WORKDIR}/${P}/${PN}"

LICENSE="LGPL-3+"
SLOT="0/${PV}"
KEYWORDS=""
IUSE="qt4 qt5"
REQUIRED_USE="^^ ( qt4 qt5 )"

RDEPEND=">=dev-haskell/hoppy-runtime-0.3:=[profile?] <dev-haskell/hoppy-runtime-0.4:=[profile?]
	>=dev-haskell/qtah-cpp-9999:=[profile?,qt4=,qt5=]
	>=dev-haskell/qtah-generator-9999:=[profile?]
	>=dev-lang/ghc-7.8.4:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
	test? ( >=dev-haskell/hunit-1.2 <dev-haskell/hunit-1.6 )
"

src_configure() {
       haskell-cabal_src_configure \
               $(cabal_flag qt4) \
               $(cabal_flag qt5)
}
