# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit git-r3 haskell-cabal

DESCRIPTION="C++ FFI generator - Runtime support"
HOMEPAGE="http://khumba.net/projects/hoppy"
EGIT_REPO_URI="https://gitlab.com/khumba/hoppy.git"
S="${WORKDIR}/${P}/runtime"

LICENSE="Apache-2.0"
SLOT="0/${PV}"
KEYWORDS=""
IUSE=""

RDEPEND=">=dev-haskell/cabal-1.20:=[profile?] <dev-haskell/cabal-2.3:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"
