# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit git-r3 haskell-cabal

DESCRIPTION="Qt bindings for Haskell - C++ library"
HOMEPAGE="http://khumba.net/projects/qtah"
EGIT_REPO_URI="https://gitlab.com/khumba/qtah.git"
S="${WORKDIR}/${P}/${PN}"

LICENSE="LGPL-3+"
SLOT="0/${PV}"
KEYWORDS=""

RDEPEND=">=dev-haskell/qtah-generator-9999:=[profile?]
	>=dev-lang/ghc-7.8.2:=
	dev-qt/qtcore:5
	dev-qt/qtgui:5
	dev-qt/qtwidgets:5
	!dev-haskell/qtah-cpp-qt5
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.0
"

src_configure() {
	haskell-cabal_src_configure --flags=qt5
}
